// Books Database - 20 books in each category (140 total)
const booksData = [{
        id: 1,
        title: "The Midnight Library",
        author: "Matt Haig",
        category: "fiction",
        price: 16.99,
        rating: 4.5,
        pages: 304,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 2,
        title: "Where the Crawdads Sing",
        author: "Delia Owens",
        category: "fiction",
        price: 18.99,
        rating: 4.7,
        pages: 384,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 3,
        title: "The Seven Husbands of Evelyn Hugo",
        author: "Taylor Jenkins Reid",
        category: "fiction",
        price: 17.99,
        rating: 4.8,
        pages: 400,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 4,
        title: "The Silent Patient",
        author: "Alex Michaelides",
        category: "fiction",
        price: 15.99,
        rating: 4.6,
        pages: 336,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 5,
        title: "Normal People",
        author: "Sally Rooney",
        category: "fiction",
        price: 16.99,
        rating: 4.4,
        pages: 288,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 6,
        title: "The Vanishing Half",
        author: "Brit Bennett",
        category: "fiction",
        price: 18.5,
        rating: 4.5,
        pages: 352,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 7,
        title: "Circe",
        author: "Madeline Miller",
        category: "fiction",
        price: 17.99,
        rating: 4.7,
        pages: 400,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 8,
        title: "The Nightingale",
        author: "Kristin Hannah",
        category: "fiction",
        price: 16.99,
        rating: 4.8,
        pages: 440,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 9,
        title: "A Gentleman in Moscow",
        author: "Amor Towles",
        category: "fiction",
        price: 19.99,
        rating: 4.6,
        pages: 496,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 10,
        title: "The Book Thief",
        author: "Markus Zusak",
        category: "fiction",
        price: 15.99,
        rating: 4.7,
        pages: 552,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 11,
        title: "The Great Alone",
        author: "Kristin Hannah",
        category: "fiction",
        price: 17.99,
        rating: 4.5,
        pages: 448,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 12,
        title: "Little Fires Everywhere",
        author: "Celeste Ng",
        category: "fiction",
        price: 16.99,
        rating: 4.4,
        pages: 368,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 13,
        title: "The Night Circus",
        author: "Erin Morgenstern",
        category: "fiction",
        price: 18.99,
        rating: 4.6,
        pages: 400,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 14,
        title: "Eleanor Oliphant Is Completely Fine",
        author: "Gail Honeyman",
        category: "fiction",
        price: 15.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 15,
        title: "The Dutch House",
        author: "Ann Patchett",
        category: "fiction",
        price: 17.99,
        rating: 4.4,
        pages: 352,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 16,
        title: "All the Light We Cannot See",
        author: "Anthony Doerr",
        category: "fiction",
        price: 18.99,
        rating: 4.8,
        pages: 544,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 17,
        title: "The Goldfinch",
        author: "Donna Tartt",
        category: "fiction",
        price: 19.99,
        rating: 4.5,
        pages: 784,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 18,
        title: "The Song of Achilles",
        author: "Madeline Miller",
        category: "fiction",
        price: 16.99,
        rating: 4.7,
        pages: 352,
        image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 19,
        title: "The Invisible Life of Addie LaRue",
        author: "V.E. Schwab",
        category: "fiction",
        price: 18.99,
        rating: 4.6,
        pages: 448,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 20,
        title: "The Overstory",
        author: "Richard Powers",
        category: "fiction",
        price: 17.99,
        rating: 4.4,
        pages: 512,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A captivating fiction story that explores deep human emotions and universal themes."
    },
    {
        id: 21,
        title: "The Love Hypothesis",
        author: "Ali Hazelwood",
        category: "romance",
        price: 14.99,
        rating: 4.6,
        pages: 384,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 22,
        title: "People We Meet on Vacation",
        author: "Emily Henry",
        category: "romance",
        price: 15.99,
        rating: 4.5,
        pages: 368,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 23,
        title: "Beach Read",
        author: "Emily Henry",
        category: "romance",
        price: 14.99,
        rating: 4.4,
        pages: 352,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 24,
        title: "The Hating Game",
        author: "Sally Thorne",
        category: "romance",
        price: 13.99,
        rating: 4.5,
        pages: 384,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 25,
        title: "Red, White & Royal Blue",
        author: "Casey McQuiston",
        category: "romance",
        price: 16.99,
        rating: 4.7,
        pages: 432,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 26,
        title: "It Ends with Us",
        author: "Colleen Hoover",
        category: "romance",
        price: 15.99,
        rating: 4.6,
        pages: 384,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 27,
        title: "The Spanish Love Deception",
        author: "Elena Armas",
        category: "romance",
        price: 14.99,
        rating: 4.4,
        pages: 437,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 28,
        title: "Book Lovers",
        author: "Emily Henry",
        category: "romance",
        price: 15.99,
        rating: 4.5,
        pages: 384,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 29,
        title: "The Kiss Quotient",
        author: "Helen Hoang",
        category: "romance",
        price: 13.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 30,
        title: "The Flatshare",
        author: "Beth O'Leary",
        category: "romance",
        price: 14.99,
        rating: 4.4,
        pages: 325,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 31,
        title: "The Unhoneymooners",
        author: "Christina Lauren",
        category: "romance",
        price: 15.99,
        rating: 4.5,
        pages: 432,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 32,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        category: "romance",
        price: 12.99,
        rating: 4.8,
        pages: 432,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 33,
        title: "The Bride Test",
        author: "Helen Hoang",
        category: "romance",
        price: 14.99,
        rating: 4.6,
        pages: 304,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 34,
        title: "Well Met",
        author: "Jen DeLuca",
        category: "romance",
        price: 13.99,
        rating: 4.4,
        pages: 336,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 35,
        title: "One Day in December",
        author: "Josie Silver",
        category: "romance",
        price: 15.99,
        rating: 4.5,
        pages: 416,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 36,
        title: "The Wedding Date",
        author: "Jasmine Guillory",
        category: "romance",
        price: 14.99,
        rating: 4.3,
        pages: 336,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 37,
        title: "From Lukov with Love",
        author: "Mariana Zapata",
        category: "romance",
        price: 16.99,
        rating: 4.6,
        pages: 523,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 38,
        title: "The Simple Wild",
        author: "K.A. Tucker",
        category: "romance",
        price: 15.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 39,
        title: "The Proposal",
        author: "Jasmine Guillory",
        category: "romance",
        price: 14.99,
        rating: 4.4,
        pages: 352,
        image: "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 40,
        title: "The Deal",
        author: "Elle Kennedy",
        category: "romance",
        price: 13.99,
        rating: 4.5,
        pages: 390,
        image: "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        summary: "A heartwarming romance that will keep you turning pages late into the night."
    },
    {
        id: 41,
        title: "Gone Girl",
        author: "Gillian Flynn",
        category: "thriller",
        price: 16.99,
        rating: 4.7,
        pages: 432,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 42,
        title: "The Girl on the Train",
        author: "Paula Hawkins",
        category: "thriller",
        price: 15.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 43,
        title: "The Woman in the Window",
        author: "A.J. Finn",
        category: "thriller",
        price: 17.99,
        rating: 4.4,
        pages: 448,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 44,
        title: "The Guest List",
        author: "Lucy Foley",
        category: "thriller",
        price: 16.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 45,
        title: "Behind Closed Doors",
        author: "B.A. Paris",
        category: "thriller",
        price: 14.99,
        rating: 4.5,
        pages: 293,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 46,
        title: "The Last Mrs. Parrish",
        author: "Liv Constantine",
        category: "thriller",
        price: 15.99,
        rating: 4.4,
        pages: 368,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 47,
        title: "The Turn of the Key",
        author: "Ruth Ware",
        category: "thriller",
        price: 16.99,
        rating: 4.3,
        pages: 368,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 48,
        title: "Sharp Objects",
        author: "Gillian Flynn",
        category: "thriller",
        price: 15.99,
        rating: 4.6,
        pages: 254,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 49,
        title: "The Couple Next Door",
        author: "Shari Lapena",
        category: "thriller",
        price: 14.99,
        rating: 4.3,
        pages: 310,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 50,
        title: "The Wife Between Us",
        author: "Greer Hendricks",
        category: "thriller",
        price: 16.99,
        rating: 4.4,
        pages: 352,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 51,
        title: "In a Dark, Dark Wood",
        author: "Ruth Ware",
        category: "thriller",
        price: 15.99,
        rating: 4.2,
        pages: 307,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 52,
        title: "The Silent Patient",
        author: "Alex Michaelides",
        category: "thriller",
        price: 15.99,
        rating: 4.7,
        pages: 336,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 53,
        title: "The Girl Before",
        author: "JP Delaney",
        category: "thriller",
        price: 14.99,
        rating: 4.3,
        pages: 342,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 54,
        title: "Sometimes I Lie",
        author: "Alice Feeney",
        category: "thriller",
        price: 15.99,
        rating: 4.4,
        pages: 277,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 55,
        title: "The Hunting Party",
        author: "Lucy Foley",
        category: "thriller",
        price: 16.99,
        rating: 4.5,
        pages: 320,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 56,
        title: "Lock Every Door",
        author: "Riley Sager",
        category: "thriller",
        price: 15.99,
        rating: 4.3,
        pages: 384,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 57,
        title: "The Other Woman",
        author: "Sandie Jones",
        category: "thriller",
        price: 14.99,
        rating: 4.4,
        pages: 336,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 58,
        title: "The Family Upstairs",
        author: "Lisa Jewell",
        category: "thriller",
        price: 16.99,
        rating: 4.5,
        pages: 352,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 59,
        title: "An Anonymous Girl",
        author: "Greer Hendricks",
        category: "thriller",
        price: 15.99,
        rating: 4.3,
        pages: 368,
        image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 60,
        title: "The Death of Mrs. Westaway",
        author: "Ruth Ware",
        category: "thriller",
        price: 16.99,
        rating: 4.4,
        pages: 368,
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
        summary: "A gripping psychological thriller with twists that will keep you on the edge of your seat."
    },
    {
        id: 61,
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        category: "psychology",
        price: 18.99,
        rating: 4.7,
        pages: 512,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 62,
        title: "The Power of Now",
        author: "Eckhart Tolle",
        category: "psychology",
        price: 16.99,
        rating: 4.6,
        pages: 236,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 63,
        title: "Man's Search for Meaning",
        author: "Viktor E. Frankl",
        category: "psychology",
        price: 14.99,
        rating: 4.8,
        pages: 184,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 64,
        title: "Influence",
        author: "Robert B. Cialdini",
        category: "psychology",
        price: 17.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 65,
        title: "The Body Keeps the Score",
        author: "Bessel van der Kolk",
        category: "psychology",
        price: 19.99,
        rating: 4.8,
        pages: 464,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 66,
        title: "Blink",
        author: "Malcolm Gladwell",
        category: "psychology",
        price: 16.99,
        rating: 4.5,
        pages: 296,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 67,
        title: "The Paradox of Choice",
        author: "Barry Schwartz",
        category: "psychology",
        price: 15.99,
        rating: 4.4,
        pages: 304,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 68,
        title: "Grit",
        author: "Angela Duckworth",
        category: "psychology",
        price: 17.99,
        rating: 4.6,
        pages: 352,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 69,
        title: "Mindset",
        author: "Carol S. Dweck",
        category: "psychology",
        price: 16.99,
        rating: 4.7,
        pages: 320,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 70,
        title: "Flow",
        author: "Mihaly Csikszentmihalyi",
        category: "psychology",
        price: 15.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 71,
        title: "The Happiness Hypothesis",
        author: "Jonathan Haidt",
        category: "psychology",
        price: 16.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 72,
        title: "Quiet",
        author: "Susan Cain",
        category: "psychology",
        price: 18.99,
        rating: 4.7,
        pages: 368,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 73,
        title: "Emotional Intelligence",
        author: "Daniel Goleman",
        category: "psychology",
        price: 17.99,
        rating: 4.6,
        pages: 384,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 74,
        title: "The Social Animal",
        author: "David Brooks",
        category: "psychology",
        price: 16.99,
        rating: 4.4,
        pages: 448,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 75,
        title: "Predictably Irrational",
        author: "Dan Ariely",
        category: "psychology",
        price: 15.99,
        rating: 4.5,
        pages: 384,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 76,
        title: "The Willpower Instinct",
        author: "Kelly McGonigal",
        category: "psychology",
        price: 16.99,
        rating: 4.6,
        pages: 272,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 77,
        title: "Stumbling on Happiness",
        author: "Daniel Gilbert",
        category: "psychology",
        price: 15.99,
        rating: 4.4,
        pages: 336,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 78,
        title: "The Marshmallow Test",
        author: "Walter Mischel",
        category: "psychology",
        price: 16.99,
        rating: 4.5,
        pages: 368,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 79,
        title: "Switch",
        author: "Chip Heath",
        category: "psychology",
        price: 17.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 80,
        title: "The Power of Habit",
        author: "Charles Duhigg",
        category: "psychology",
        price: 16.99,
        rating: 4.7,
        pages: 371,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An insightful exploration of the human mind and behavior backed by scientific research."
    },
    {
        id: 81,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        category: "classics",
        price: 12.99,
        rating: 4.9,
        pages: 336,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 82,
        title: "1984",
        author: "George Orwell",
        category: "classics",
        price: 13.99,
        rating: 4.8,
        pages: 328,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 83,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        category: "classics",
        price: 11.99,
        rating: 4.7,
        pages: 180,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 84,
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        category: "classics",
        price: 12.99,
        rating: 4.8,
        pages: 532,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 85,
        title: "Wuthering Heights",
        author: "Emily Brontë",
        category: "classics",
        price: 11.99,
        rating: 4.6,
        pages: 416,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 86,
        title: "Moby-Dick",
        author: "Herman Melville",
        category: "classics",
        price: 14.99,
        rating: 4.5,
        pages: 704,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 87,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        category: "classics",
        price: 13.99,
        rating: 4.6,
        pages: 277,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 88,
        title: "Brave New World",
        author: "Aldous Huxley",
        category: "classics",
        price: 12.99,
        rating: 4.7,
        pages: 288,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 89,
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        category: "classics",
        price: 11.99,
        rating: 4.7,
        pages: 254,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 90,
        title: "The Count of Monte Cristo",
        author: "Alexandre Dumas",
        category: "classics",
        price: 15.99,
        rating: 4.8,
        pages: 1276,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 91,
        title: "Anna Karenina",
        author: "Leo Tolstoy",
        category: "classics",
        price: 14.99,
        rating: 4.7,
        pages: 864,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 92,
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        category: "classics",
        price: 13.99,
        rating: 4.8,
        pages: 671,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 93,
        title: "Frankenstein",
        author: "Mary Shelley",
        category: "classics",
        price: 10.99,
        rating: 4.6,
        pages: 280,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 94,
        title: "The Adventures of Huckleberry Finn",
        author: "Mark Twain",
        category: "classics",
        price: 11.99,
        rating: 4.5,
        pages: 366,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 95,
        title: "Little Women",
        author: "Louisa May Alcott",
        category: "classics",
        price: 12.99,
        rating: 4.7,
        pages: 759,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 96,
        title: "The Scarlet Letter",
        author: "Nathaniel Hawthorne",
        category: "classics",
        price: 11.99,
        rating: 4.4,
        pages: 272,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 97,
        title: "Dracula",
        author: "Bram Stoker",
        category: "classics",
        price: 12.99,
        rating: 4.6,
        pages: 488,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 98,
        title: "The Odyssey",
        author: "Homer",
        category: "classics",
        price: 13.99,
        rating: 4.7,
        pages: 541,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 99,
        title: "The Iliad",
        author: "Homer",
        category: "classics",
        price: 13.99,
        rating: 4.6,
        pages: 683,
        image: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 100,
        title: "The Brothers Karamazov",
        author: "Fyodor Dostoevsky",
        category: "classics",
        price: 15.99,
        rating: 4.8,
        pages: 796,
        image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
        summary: "A timeless literary masterpiece that has influenced generations of readers."
    },
    {
        id: 101,
        title: "Atomic Habits",
        author: "James Clear",
        category: "personal-development",
        price: 16.99,
        rating: 4.8,
        pages: 320,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 102,
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        category: "personal-development",
        price: 15.99,
        rating: 4.7,
        pages: 381,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 103,
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        category: "personal-development",
        price: 14.99,
        rating: 4.7,
        pages: 288,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 104,
        title: "Think and Grow Rich",
        author: "Napoleon Hill",
        category: "personal-development",
        price: 13.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 105,
        title: "The Subtle Art of Not Giving a F*ck",
        author: "Mark Manson",
        category: "personal-development",
        price: 15.99,
        rating: 4.5,
        pages: 224,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 106,
        title: "Can't Hurt Me",
        author: "David Goggins",
        category: "personal-development",
        price: 17.99,
        rating: 4.8,
        pages: 364,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 107,
        title: "The Four Agreements",
        author: "Don Miguel Ruiz",
        category: "personal-development",
        price: 12.99,
        rating: 4.7,
        pages: 160,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 108,
        title: "You Are a Badass",
        author: "Jen Sincero",
        category: "personal-development",
        price: 14.99,
        rating: 4.6,
        pages: 256,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 109,
        title: "Deep Work",
        author: "Cal Newport",
        category: "personal-development",
        price: 16.99,
        rating: 4.7,
        pages: 296,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 110,
        title: "The Gifts of Imperfection",
        author: "Brené Brown",
        category: "personal-development",
        price: 14.99,
        rating: 4.6,
        pages: 160,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 111,
        title: "Start with Why",
        author: "Simon Sinek",
        category: "personal-development",
        price: 15.99,
        rating: 4.6,
        pages: 256,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 112,
        title: "The 5 AM Club",
        author: "Robin Sharma",
        category: "personal-development",
        price: 16.99,
        rating: 4.5,
        pages: 336,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 113,
        title: "Daring Greatly",
        author: "Brené Brown",
        category: "personal-development",
        price: 15.99,
        rating: 4.7,
        pages: 320,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 114,
        title: "Essentialism",
        author: "Greg McKeown",
        category: "personal-development",
        price: 15.99,
        rating: 4.6,
        pages: 272,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 115,
        title: "The Miracle Morning",
        author: "Hal Elrod",
        category: "personal-development",
        price: 14.99,
        rating: 4.5,
        pages: 194,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 116,
        title: "The Obstacle Is the Way",
        author: "Ryan Holiday",
        category: "personal-development",
        price: 15.99,
        rating: 4.6,
        pages: 224,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 117,
        title: "12 Rules for Life",
        author: "Jordan B. Peterson",
        category: "personal-development",
        price: 17.99,
        rating: 4.5,
        pages: 409,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 118,
        title: "Who Moved My Cheese?",
        author: "Spencer Johnson",
        category: "personal-development",
        price: 11.99,
        rating: 4.4,
        pages: 96,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 119,
        title: "The War of Art",
        author: "Steven Pressfield",
        category: "personal-development",
        price: 13.99,
        rating: 4.6,
        pages: 190,
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 120,
        title: "The Magic of Thinking Big",
        author: "David J. Schwartz",
        category: "personal-development",
        price: 14.99,
        rating: 4.6,
        pages: 320,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "A transformative guide that provides practical strategies for personal growth and success."
    },
    {
        id: 121,
        title: "Educated",
        author: "Tara Westover",
        category: "biography",
        price: 17.99,
        rating: 4.8,
        pages: 385,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 122,
        title: "Becoming",
        author: "Michelle Obama",
        category: "biography",
        price: 19.99,
        rating: 4.9,
        pages: 448,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 123,
        title: "Steve Jobs",
        author: "Walter Isaacson",
        category: "biography",
        price: 18.99,
        rating: 4.7,
        pages: 656,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 124,
        title: "Long Walk to Freedom",
        author: "Nelson Mandela",
        category: "biography",
        price: 16.99,
        rating: 4.8,
        pages: 656,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 125,
        title: "The Diary of a Young Girl",
        author: "Anne Frank",
        category: "biography",
        price: 12.99,
        rating: 4.9,
        pages: 283,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 126,
        title: "Unbroken",
        author: "Laura Hillenbrand",
        category: "biography",
        price: 17.99,
        rating: 4.8,
        pages: 473,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 127,
        title: "The Autobiography of Malcolm X",
        author: "Malcolm X",
        category: "biography",
        price: 15.99,
        rating: 4.7,
        pages: 466,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 128,
        title: "Einstein: His Life and Universe",
        author: "Walter Isaacson",
        category: "biography",
        price: 18.99,
        rating: 4.6,
        pages: 675,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 129,
        title: "The Glass Castle",
        author: "Jeannette Walls",
        category: "biography",
        price: 16.99,
        rating: 4.7,
        pages: 288,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 130,
        title: "Born a Crime",
        author: "Trevor Noah",
        category: "biography",
        price: 17.99,
        rating: 4.8,
        pages: 304,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 131,
        title: "Alexander Hamilton",
        author: "Ron Chernow",
        category: "biography",
        price: 19.99,
        rating: 4.7,
        pages: 832,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 132,
        title: "When Breath Becomes Air",
        author: "Paul Kalanithi",
        category: "biography",
        price: 15.99,
        rating: 4.8,
        pages: 256,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 133,
        title: "I Am Malala",
        author: "Malala Yousafzai",
        category: "biography",
        price: 16.99,
        rating: 4.7,
        pages: 327,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 134,
        title: "Into the Wild",
        author: "Jon Krakauer",
        category: "biography",
        price: 15.99,
        rating: 4.6,
        pages: 207,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 135,
        title: "The Wright Brothers",
        author: "David McCullough",
        category: "biography",
        price: 17.99,
        rating: 4.7,
        pages: 320,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 136,
        title: "The Immortal Life of Henrietta Lacks",
        author: "Rebecca Skloot",
        category: "biography",
        price: 16.99,
        rating: 4.6,
        pages: 381,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 137,
        title: "Team of Rivals",
        author: "Doris Kearns Goodwin",
        category: "biography",
        price: 20.99,
        rating: 4.7,
        pages: 944,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 138,
        title: "Leonardo da Vinci",
        author: "Walter Isaacson",
        category: "biography",
        price: 19.99,
        rating: 4.6,
        pages: 624,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 139,
        title: "Wild Swans",
        author: "Jung Chang",
        category: "biography",
        price: 18.99,
        rating: 4.8,
        pages: 524,
        image: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    },
    {
        id: 140,
        title: "Open",
        author: "Andre Agassi",
        category: "biography",
        price: 17.99,
        rating: 4.7,
        pages: 388,
        image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
        summary: "An inspiring true story that reveals the extraordinary life of a remarkable individual."
    }
];